# Generated by Django 4.2.6 on 2023-12-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('Day', models.DateField(auto_now_add=True, null=True)),
                ('check_in_date', models.DateField(auto_now_add=True, null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('Total_hours', models.FloatField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employees')),
            ],
        ),
    ]
