# Generated by Django 4.2.6 on 2023-12-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_check_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=50)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='check_in',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='check_in',
            name='ip_address',
        ),
    ]
